import { SettingsFormField } from "@devvit/public-api";
import { SightengineResponse } from "../checkSightEngineAPI.js";
import { DetectionBase } from "./DetectionBase.js";

enum ModuleSetting {
    Threshold = "GenAI_Threshold",
}

export class DetectGenAI extends DetectionBase {
    public name = "GenAI";
    public friendlyName = "Generative AI Detection";
    public helpText = "Detects images that are likely generated by AI, such as ChatGPT, Dall-E and others.";
    public sightengineType = "genai";

    override defaultEnabledForMenu = true;

    override moduleSettings: SettingsFormField[] = [
        {
            type: "number",
            label: "Threshold to report",
            name: ModuleSetting.Threshold,
            helpText: "App will report the post if the AI content likelihood is greater than this percentage.",
            defaultValue: 80,
            onValidate: event => this.validatePercentage(event),
        },
    ];

    private getAILikelihood (sightEngineResponse: SightengineResponse): number | undefined {
        if (!sightEngineResponse.type?.ai_generated) {
            return;
        }

        return Math.round(sightEngineResponse.type.ai_generated * 100);
    }

    public detectProactive (sightEngineResponse: SightengineResponse): string | undefined {
        const aiLikelihood = this.getAILikelihood(sightEngineResponse);
        if (aiLikelihood === undefined) {
            return;
        }

        if (aiLikelihood > this.getSetting<number>(ModuleSetting.Threshold, 80)) {
            return `AI Likelihood: ${aiLikelihood}%.`;
        }
    }

    public detectByMenu (sightEngineResponse: SightengineResponse): string | undefined {
        const aiLikelihood = this.getAILikelihood(sightEngineResponse);
        if (aiLikelihood === undefined) {
            return;
        }

        return `AI Likelihood: ${aiLikelihood}%`;
    }
}
